/*
 * Hospital Equipment Management API
 *
 * Equipment and requests management system for hospital
 *
 * API version: 1.0.0
 * Contact: example@mail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fpjp

type Room struct {

	// Unique identifier of the room
	Id string `json:"id"`

	// Identifier of the department the room belongs to
	DepartmentId string `json:"department_id"`

	// Name of the room
	Name string `json:"name"`
}
