/*
 * Hospital Equipment Management API
 *
 * Equipment and requests management system for hospital
 *
 * API version: 1.0.0
 * Contact: example@mail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fpjp

type Request struct {

	// Unique identifier of the request
	Id string `json:"id" bson:"id"`

	// Identifier of the room the request is associated with
	Room string `json:"room" bson:"room"`

	// Type of the request
	Type string `json:"type" bson:"type"`

	// Name of the equipment requested or to be repaired
	Name string `json:"name" bson:"name"`

	// Number of items requested (only applicable for missing-equipment requests)
	Count *int32 `json:"count,omitempty" bson:"count,omitempty"`

	// Detailed description of the request
	Description string `json:"description" bson:"description"`
}
