/*
 * Hospital Equipment Management API
 *
 * Equipment and requests management system for hospital
 *
 * API version: 1.0.0
 * Contact: example@mail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fpjp

type Equipment struct {

	// Unique identifier of the equipment
	Id string `json:"id"`

	// Identifier of the room the equipment belongs to
	RoomId string `json:"room_id"`

	// Type of the equipment
	Type string `json:"type"`

	// Name of the equipment
	Name string `json:"name"`

	// Number of equipment items available
	Count int32 `json:"count"`
}
